

name: Run commitlint of last commit

on:
  push:
    branches: '**'
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    uses: jeeshan12/resusable_workflows/.github/workflows/commitlint.yaml@v2.2.0