

name: Run commit lint for last commit

on:
  pull_request:
    branches: [ "main" ]

jobs:
  commitlint:
    uses: jeeshan12/resusable_workflows/.github/workflows/commitlint.yaml@fix-commitlint-worfklow