

name: Run Gitleaks on commits

on: [pull_request, push, workflow_dispatch]

jobs:
  commitlint:
    uses: jeeshan12/resusable_workflows/.github/workflows/gitleaks-scan.yaml@feat-gitleaks
    secrets: inherit