

name: Run Gitleaks on commits

on: [pull_request, push, workflow_dispatch]

jobs:
  gitleaks:
    uses: jeeshan12/resusable_workflows/.github/workflows/gitleaks-scan.yaml@feat-gitleaks
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}