

name: Run Gitleaks on commits

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
  workflow_dispatch:

jobs:
  gitleaks:
    uses: jeeshan12/resusable_workflows/.github/workflows/gitleaks-scan.yaml@feat-gitleaks
    secrets:
      token: ${{ secrets.GITHUBLEAKS_TOKEN }}
    permissions: read-all