

name: Run Gitleaks on commits

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
  workflow_dispatch:

jobs:
  gitleaks:
    uses: jeeshan12/resusable_workflows/.github/workflows/gitleaks-scan.yaml@v2.4.0
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
