name: Run Selenium tests

on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main
  workflow_dispatch:

jobs:

  e2e:
    strategy:
      matrix:
        xml: [ "src/test/resources/xmlfiles/testng.xml", "src/test/resources/xmlfiles/framework-tests.xml" ]
    name: e2e-${{ matrix.xml }}
    uses: jeeshan12/resusable_workflows/.github/workflows/selenium-e2e.yaml@feat-publish-reports
    with:
      java-version: "21"
      xml-file: ${{ matrix.xml }}
      pom-file: "pom.xml"
      file-path: "target/surefire-reports/TEST-TestSuite.xml"
