name: Run Selenium tests

on:
  workflow_dispatch:

jobs:

  e2e:
    name: e2e-run
    uses: jeeshan12/resusable_workflows/.github/workflows/selenium-e2e.yaml@v2.10.1
    permissions:
      checks: write
      pull-requests: write
    with:
      java-version: "21"
      xml-file: "src/test/resources/xmlfiles/testng.xml"
      pom-file: "pom.xml"
      file-path: "target/surefire-reports/TEST-TestSuite.xml"
