

name: Run Sonarcloud on repository

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
  workflow_dispatch:

jobs:
  sonarcloud-scan:
    uses: jeeshan12/resusable_workflows/.github/workflows/sonarcloud-scan.yaml@v2.5.1
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
    with:
     repository-name: jeeshan12_AWM_AutomationFramework
     java-version: "21"
